// <auto-generated />
using BackendInventario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendInventario.Migrations
{
    [DbContext(typeof(InventarioContext))]
    [Migration("20260312115855_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BackendInventario.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Articulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Imagen = "https://loremflickr.com/300/200/monitor",
                            Nombre = "Monitor Xiaomi A27Ui 4K",
                            Stock = 12
                        },
                        new
                        {
                            Id = 2,
                            Imagen = "https://loremflickr.com/300/200/keyboard",
                            Nombre = "Teclado Mecánico Logitech G Pro",
                            Stock = 8
                        },
                        new
                        {
                            Id = 3,
                            Imagen = "https://loremflickr.com/300/200/computermouse",
                            Nombre = "Ratón Inalámbrico Razer Viper",
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            Imagen = "https://loremflickr.com/300/200/headphones",
                            Nombre = "Auriculares HyperX Cloud II",
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            Imagen = "https://loremflickr.com/300/200/mousepad",
                            Nombre = "Alfombrilla Gaming XL",
                            Stock = 50
                        },
                        new
                        {
                            Id = 6,
                            Imagen = "https://loremflickr.com/300/200/webcam",
                            Nombre = "Webcam Logitech C920",
                            Stock = 10
                        },
                        new
                        {
                            Id = 7,
                            Imagen = "https://loremflickr.com/300/200/desk,setup",
                            Nombre = "Soporte para Monitor Doble",
                            Stock = 5
                        },
                        new
                        {
                            Id = 8,
                            Imagen = "https://loremflickr.com/300/200/microphone",
                            Nombre = "Micrófono Blue Yeti",
                            Stock = 7
                        },
                        new
                        {
                            Id = 9,
                            Imagen = "https://loremflickr.com/300/200/harddrive",
                            Nombre = "Disco Duro Externo 2TB",
                            Stock = 25
                        },
                        new
                        {
                            Id = 10,
                            Imagen = "https://loremflickr.com/300/200/ram,computer",
                            Nombre = "Memoria RAM 16GB DDR4",
                            Stock = 30
                        },
                        new
                        {
                            Id = 11,
                            Imagen = "https://loremflickr.com/300/200/gpu,nvidia",
                            Nombre = "Tarjeta Gráfica RTX 4060",
                            Stock = 4
                        },
                        new
                        {
                            Id = 12,
                            Imagen = "https://loremflickr.com/300/200/cpu,intel",
                            Nombre = "Procesador Intel i7-13700K",
                            Stock = 6
                        },
                        new
                        {
                            Id = 13,
                            Imagen = "https://loremflickr.com/300/200/motherboard",
                            Nombre = "Placa Base ASUS ROG Strix",
                            Stock = 3
                        },
                        new
                        {
                            Id = 14,
                            Imagen = "https://loremflickr.com/300/200/powersupply",
                            Nombre = "Fuente de Alimentación 750W",
                            Stock = 12
                        },
                        new
                        {
                            Id = 15,
                            Imagen = "https://loremflickr.com/300/200/pccase",
                            Nombre = "Caja PC Cooler Master",
                            Stock = 8
                        },
                        new
                        {
                            Id = 16,
                            Imagen = "https://loremflickr.com/300/200/cpucooler",
                            Nombre = "Ventilador CPU Noctua",
                            Stock = 15
                        },
                        new
                        {
                            Id = 17,
                            Imagen = "https://loremflickr.com/300/200/ssd",
                            Nombre = "SSD NVMe 1TB Samsung",
                            Stock = 40
                        },
                        new
                        {
                            Id = 18,
                            Imagen = "https://loremflickr.com/300/200/usbhub",
                            Nombre = "Hub USB-C 7 en 1",
                            Stock = 22
                        },
                        new
                        {
                            Id = 19,
                            Imagen = "https://loremflickr.com/300/200/speakers",
                            Nombre = "Altavoces Creative 2.1",
                            Stock = 11
                        },
                        new
                        {
                            Id = 20,
                            Imagen = "https://loremflickr.com/300/200/xbox,controller",
                            Nombre = "Mando Xbox Carbon Black",
                            Stock = 18
                        },
                        new
                        {
                            Id = 21,
                            Imagen = "https://loremflickr.com/300/200/gamingchair",
                            Nombre = "Silla Gaming Ergonómica",
                            Stock = 5
                        },
                        new
                        {
                            Id = 22,
                            Imagen = "https://loremflickr.com/300/200/curvedmonitor",
                            Nombre = "Monitor Curvo 34 Pulgadas",
                            Stock = 2
                        },
                        new
                        {
                            Id = 23,
                            Imagen = "https://loremflickr.com/300/200/cleaning",
                            Nombre = "Kit de Limpieza Pantallas",
                            Stock = 100
                        },
                        new
                        {
                            Id = 24,
                            Imagen = "https://loremflickr.com/300/200/ringlight",
                            Nombre = "Luz de Anillo LED 10\"",
                            Stock = 35
                        },
                        new
                        {
                            Id = 25,
                            Imagen = "https://loremflickr.com/300/200/bluetooth,usb",
                            Nombre = "Adaptador Bluetooth 5.0",
                            Stock = 60
                        },
                        new
                        {
                            Id = 26,
                            Imagen = "https://loremflickr.com/300/200/charger",
                            Nombre = "Cargador Rápido 65W",
                            Stock = 45
                        },
                        new
                        {
                            Id = 27,
                            Imagen = "https://loremflickr.com/300/200/laptop",
                            Nombre = "Portátil Workstation 16\"",
                            Stock = 4
                        },
                        new
                        {
                            Id = 28,
                            Imagen = "https://loremflickr.com/300/200/drawingtablet",
                            Nombre = "Tableta Digitalizadora",
                            Stock = 9
                        },
                        new
                        {
                            Id = 29,
                            Imagen = "https://loremflickr.com/300/200/router,wifi",
                            Nombre = "Router WiFi 6 Pro",
                            Stock = 14
                        },
                        new
                        {
                            Id = 30,
                            Imagen = "https://loremflickr.com/300/200/streaming,setup",
                            Nombre = "Stream Deck MK.2",
                            Stock = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
